### GET request to example server
GET http://localhost:8080/v1/accounts
Accept: application/json

### GET request to example server
GET http://localhost:8080/v1/accounts?ownerId=767a7790-7a7b-4fc0-b352-aaffc5a987c0
Accept: application/json

###
GET http://localhost:8080/v1/accounts/DE12345678901234567869
Accept: application/json

###
POST http://localhost:8080/v1/accounts
Accept: application/json
Content-Type: application/json

{
  "iban": "DE12345678901234567869",
  "accountType": "current",
  "ownerId": "767a7790-7a7b-4fc0-b352-aaffc5a987c9"
}

####
DELETE http://localhost:8080/v1/accounts/DE12345678901234567869


###
GET http://localhost:8080/v1/accounts/DE00000000000000000001/transactions
Accept: application/json

###
POST http://localhost:8080/v1/accounts/DE00000000000000000001/deposit
Accept: application/json
Content-Type: application/json

{
  "amount": 7.0,
  "purpose": "Test Post",
  "timestamp": "2026-06-25T23:39:00.000Z"
}

###
POST http://localhost:8080/v1/accounts/DE00000000000000000001/withdrawal
Accept: application/json
Content-Type: application/json

{
  "amount": 50.0,
  "purpose": "Test Moneten withdr",
  "timestamp": "jetzt"
}