### GET request to example server
GET http://localhost:8080/v1/customers
Accept: application/json

###
POST http://localhost:8080/v1/customers
Accept: application/json
Content-Type: application/json

{
  "name": "Max Beispiel3",
  "city": "Hamburg"
}

###
PUT http://localhost:8080/v1/customers/c1f8b00f-0a78-4724-9202-611a3fda7ff9
Accept: application/json
Content-Type: application/json

{
  "name": "Max",
  "city": "Hamburg"
}

### GET request to example server
GET http://localhost:8080/v1/customers/c1f8b00f-0a78-4724-9202-611a3fda7ff9
Accept: application/json

####
DELETE http://localhost:8080/v1/customers/c1f8b00f-0a78-4724-9202-611a3fda7ff9